# Generated by Django 6.0.2 on 2026-02-10 09:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=api.models.generate_acc_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=api.models.generate_cust_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=api.models.generate_prod_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.CharField(default=api.models.generate_pur_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id',
            field=models.CharField(default=api.models.generate_qtn_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.CharField(default=api.models.generate_sale_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='id',
            field=models.CharField(default=api.models.generate_log_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.CharField(default=api.models.generate_store_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=api.models.generate_user_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
