# Generated by Django 6.0.2 on 2026-02-10 09:41

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_id_alter_customer_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=api.models.generate_trans_id, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('expense', 'Expense'), ('sale_return', 'Sale Return')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.store')),
            ],
        ),
    ]
