# Generated by Django 6.0.2 on 2026-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_attendance_leave_payroll_performancereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('hr_manager', 'HR Manager'), ('sales_manager', 'Sales Manager'), ('inventory_manager', 'Inventory Manager'), ('accountant', 'Accountant'), ('employee', 'Employee'), ('user', 'User'), ('super_admin', 'Super Admin')], default='staff', max_length=50),
        ),
    ]
