# Generated by Django 6.0 on 2026-02-23 16:57

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.CharField(default=api.models.generate_pt_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('days', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='api.store')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(default=api.models.generate_sup_id, max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('documents', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=50)),
                ('rating', models.IntegerField(default=5)),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='api.paymentterm')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.store')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCustomField',
            fields=[
                ('id', models.CharField(default=api.models.generate_scf_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('show_on_receipt', models.BooleanField(default=False)),
                ('hide_label', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_custom_fields', to='api.store')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCustomFieldValue',
            fields=[
                ('id', models.CharField(default=api.models.generate_scfv_id, max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suppliercustomfield')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.CharField(default=api.models.generate_doc_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_documents', to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.CharField(default=api.models.generate_stx_id, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('opening_balance', 'Opening Balance')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.supplier')),
            ],
        ),
    ]
