# Generated by Django 6.0 on 2026-02-23 18:37

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paymentterm_supplier_suppliercustomfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.CharField(default=api.models.generate_recv_id, max_length=50, primary_key=True, serialize=False)),
                ('receiving_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings', to='api.account')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings', to='api.purchaseorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to='api.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.CharField(default=api.models.generate_ri_id, max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upc', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_items', to='api.product')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.receiving')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
    ]
