# Generated by Django 6.0 on 2026-02-26 17:10

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sale_discount_amount_sale_status_sale_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.CharField(default=api.models.generate_chq_id, max_length=50, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=20)),
                ('party_id', models.CharField(max_length=50)),
                ('party_name', models.CharField(max_length=255)),
                ('cheque_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField()),
                ('clearing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='api.store')),
            ],
        ),
    ]
