# Generated by Django 6.0 on 2026-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_is_kit_product_limited_qty_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(default='POS', max_length=50),
        ),
    ]
