# Generated by Django 6.0 on 2026-03-14 19:15

from django.db import migrations


def seed_features(apps, schema_editor):
    Feature = apps.get_model('api', 'Feature')
    ai_features = [
        ("Business Analyst", "Chat with your ERP data for insights."),
        ("Inventory Forecast", "Predicts stockouts based on sales velocity."),
        ("Invoice OCR", "Automatically scans and populates purchase orders from receipt images."),
        ("Reorder Optimization", "Recommends optimal minStock and reorder quantities."),
        ("HR & Performance AI", "Analyzes attendance patterns, employee risk, and shift scheduling."),
        ("Recruitment AI", "Parses and scores resumes automatically."),
        ("HR Assistant", "A dedicated policy-aware chatbot for staff."),
    ]
    for name, desc in ai_features:
        Feature.objects.get_or_create(name=name, defaults={'description': desc})

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_client_id_alter_clientfeature_id_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_features),
    ]
