# Generated by Django 6.0 on 2026-03-26 13:09

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.CharField(default=api.models.generate_perm_id, max_length=50, primary_key=True, serialize=False)),
                ('permissions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
